//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COPTD
    {
        public int no { get; set; }
        public string COMPANY { get; set; }
        public string TA001 { get; set; }
        public string type { get; set; }
        public string billNo { get; set; }
        public string sno { get; set; }
        public string pno { get; set; }
        public string batchNo { get; set; }
        public string COP_num { get; set; }
        public string isfail { get; set; }
        public System.DateTime create_date { get; set; }
        public string user { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public string update_user { get; set; }
    }
}
