//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDA_Log
    {
        public string text { get; set; }
        public string table { get; set; }
        public string user { get; set; }
        public string COMPANY { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
